project_id = "usgqmmfigvkmxneoegig"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-notifications]
    verify_jwt = false
  [functions.community-notify]
    verify_jwt = false
  [functions.find-ayah]
    verify_jwt = false
  [functions.stt]
    verify_jwt = false
  [functions.stt-chunk]
    verify_jwt = false
  [functions.score-tajwid]
    verify_jwt = false
  [functions.elevenlabs-tts]
    verify_jwt = false
